version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never
artifacts:
  files:
    - '**/*'
